In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import seaborn as sns
pd.set_option('display.precision',4)
Claims_df = pd.read_csv("Iteration 2.csv")

In [7]:
Claims_df.shape

(31574, 21)

In [23]:
Claims_df.describe(include='all')

,CLAIM_KEY,SVC_LN_KEY,DIAG_CD,DIAG_DESC,Category,DIAG_CAT_CD,DIAG_CAT_NAME,DIAG_CLASS_NAME,PLACE_OF_SVC_CD,PLACE_OF_SVC_NAME,...,PAT_AGE,PAT_MBR_GENDER_CD,PROC_SVC_KEY,BILL_AMT_CALC,PMT_AMT_CALC,SVC_BEG_DT,Service_Beg_Date,SVC_END_DT,Service_End_Date,Difference
count,3.1574e+04,3.1574e+04,31574,31574,31574,31574,31574,31574,31574.0000,31574,...,31574.0000,31574,31574.0000,31574.0000,31574.0000,31574.0000,31574.0000,31574.0000,31574.0000,31574.0000
unique,NaN,NaN,585,585,5,126,126,1,NaN,17,...,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,C9000,MULTIPLE MYELOMA NOT HAVING ACHIEVED REMISSION,Malignant,C50,MALIGNANT NEOPLASM OF BREAST,NEOPLASMS,NaN,ON CAMPUS-OUTPATIENT HOSPITAL,...,NaN,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,1280,1280,25506,4827,4827,31574,NaN,11996,...,NaN,17128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,4.9529e+08,6.6210e+08,NaN,NaN,NaN,NaN,NaN,NaN,40.8032,NaN,...,53.5732,NaN,23256.5502,1529.1259,318.1563,201957.1472,43821.4186,201957.1690,43821.9921,0.5735
std,2.8910e+08,1.6410e+08,NaN,NaN,NaN,NaN,NaN,NaN,29.6990,NaN,...,11.9570,NaN,8795.7513,8090.9108,2498.8457,49.4695,189.4140,49.4516,188.7211,4.1230
min,4.1511e+04,4.8994e+08,NaN,NaN,NaN,NaN,NaN,NaN,1.0000,NaN,...,0.0000,NaN,0.0000,0.0000,0.0000,201901.0000,43466.0000,201901.0000,43466.0000,0.0000
25%,2.4474e+08,5.3142e+08,NaN,NaN,NaN,NaN,NaN,NaN,22.0000,NaN,...,48.0000,NaN,18085.0000,53.1725,1.6000,201907.0000,43647.0000,201907.0000,43647.0000,0.0000
50%,5.0337e+08,6.0757e+08,NaN,NaN,NaN,NaN,NaN,NaN,22.0000,NaN,...,56.0000,NaN,27438.0000,165.0000,18.0900,202001.0000,43831.0000,202001.0000,43831.0000,0.0000
75%,7.4121e+08,7.1948e+08,NaN,NaN,NaN,NaN,NaN,NaN,81.0000,NaN,...,62.0000,NaN,28798.0000,422.0000,112.6500,202006.0000,43983.0000,202006.0000,43983.0000,0.0000
max,9.9968e+08,1.3421e+09,NaN,NaN,NaN,NaN,NaN,NaN,99.0000,NaN,...,101.0000,NaN,33403.0000,457309.9200,199214.9700,202012.0000,44166.0000,202012.0000,44166.0000,31.0000

In [9]:
Claims_df.tail(10)

,CLAIM_KEY,SVC_LN_KEY,DIAG_CD,DIAG_DESC,Category,DIAG_CAT_CD,DIAG_CAT_NAME,DIAG_CLASS_NAME,PLACE_OF_SVC_CD,PLACE_OF_SVC_NAME,...,PAT_AGE,PAT_MBR_GENDER_CD,PROC_SVC_KEY,BILL_AMT_CALC,PMT_AMT_CALC,SVC_BEG_DT,Service_Beg_Date,SVC_END_DT,Service_End_Date,Difference
31564,647940595,1342113449,C189,"MALIGNANT NEOPLASM OF COLON, UNSPECIFIED",Malignant,C18,MALIGNANT NEOPLASM OF COLON,NEOPLASMS,22,ON CAMPUS-OUTPATIENT HOSPITAL,...,48,M,30382,236.00,45.54,202002,43862,202002,43862,0
31565,647940595,1342113450,C189,"MALIGNANT NEOPLASM OF COLON, UNSPECIFIED",Malignant,C18,MALIGNANT NEOPLASM OF COLON,NEOPLASMS,22,ON CAMPUS-OUTPATIENT HOSPITAL,...,48,M,30390,183.00,28.87,202002,43862,202002,43862,0
31566,647940595,1342113451,C189,"MALIGNANT NEOPLASM OF COLON, UNSPECIFIED",Malignant,C18,MALIGNANT NEOPLASM OF COLON,NEOPLASMS,22,ON CAMPUS-OUTPATIENT HOSPITAL,...,48,M,2,2.97,1.30,202002,43862,202002,43862,0
31567,647940595,1342113452,C189,"MALIGNANT NEOPLASM OF COLON, UNSPECIFIED",Malignant,C18,MALIGNANT NEOPLASM OF COLON,NEOPLASMS,22,ON CAMPUS-OUTPATIENT HOSPITAL,...,48,M,30404,706.00,219.78,202002,43862,202002,43862,0
31568,647940595,1342113453,C189,"MALIGNANT NEOPLASM OF COLON, UNSPECIFIED",Malignant,C18,MALIGNANT NEOPLASM OF COLON,NEOPLASMS,22,ON CAMPUS-OUTPATIENT HOSPITAL,...,48,M,14806,16293.22,2614.42,202002,43862,202002,43862,0
31569,647940595,1342113454,C189,"MALIGNANT NEOPLASM OF COLON, UNSPECIFIED",Malignant,C18,MALIGNANT NEOPLASM OF COLON,NEOPLASMS,22,ON CAMPUS-OUTPATIENT HOSPITAL,...,48,M,14825,66.48,2.80,202002,43862,202002,43862,0
31570,647940595,1342113455,C189,"MALIGNANT NEOPLASM OF COLON, UNSPECIFIED",Malignant,C18,MALIGNANT NEOPLASM OF COLON,NEOPLASMS,22,ON CAMPUS-OUTPATIENT HOSPITAL,...,48,M,15020,146.51,1.60,202002,43862,202002,43862,0
31571,685257057,1342132736,C8590,"NON-HODGKIN LYMPHOMA, UNSPECIFIED, UNSPECIFIED...",Malignant,C85,OTHER & UNSPECIFIED TYPES NON-HODGKINS LYMPHOMA,NEOPLASMS,81,INDEPENDENT LABORATORY,...,59,M,29204,119.00,49.46,202011,44136,202011,44136,0
31572,685257057,1342132737,C8590,"NON-HODGKIN LYMPHOMA, UNSPECIFIED, UNSPECIFIED...",Malignant,C85,OTHER & UNSPECIFIED TYPES NON-HODGKINS LYMPHOMA,NEOPLASMS,81,INDEPENDENT LABORATORY,...,59,M,29205,1610.00,418.78,202011,44136,202011,44136,0
31573,685257057,1342132740,C8590,"NON-HODGKIN LYMPHOMA, UNSPECIFIED, UNSPECIFIED...",Malignant,C85,OTHER & UNSPECIFIED TYPES NON-HODGKINS LYMPHOMA,NEOPLASMS,81,INDEPENDENT LABORATORY,...,59,M,29284,476.00,208.46,202011,44136,202011,44136,0

In [11]:
Claims_df.head(6)

,CLAIM_KEY,SVC_LN_KEY,DIAG_CD,DIAG_DESC,Category,DIAG_CAT_CD,DIAG_CAT_NAME,DIAG_CLASS_NAME,PLACE_OF_SVC_CD,PLACE_OF_SVC_NAME,...,PAT_AGE,PAT_MBR_GENDER_CD,PROC_SVC_KEY,BILL_AMT_CALC,PMT_AMT_CALC,SVC_BEG_DT,Service_Beg_Date,SVC_END_DT,Service_End_Date,Difference
0,78266357,489936501,C7951,SECONDARY MALIGNANT NEOPLASM OF BONE,Malignant,C79,SECONDARY MALIGNANT NEOPLASM OF OTHER AND UNSPEC,NEOPLASMS,22,ON CAMPUS-OUTPATIENT HOSPITAL,...,61,F,22908,10450.52,1779.0,201901,43466,201901,43466,0
1,70650677,491901115,D167,"BENIGN NEOPLASM OF RIBS, STERNUM AND CLAVICLE",Benign,D16,BENIGN NEOPLASM OF BONE AND ARTICULAR CARTILAGE,NEOPLASMS,22,ON CAMPUS-OUTPATIENT HOSPITAL,...,32,F,26874,318.00,0.0,201901,43466,201901,43466,0
2,726223583,492031631,D110,BENIGN NEOPLASM OF PAROTID GLAND,Benign,D11,BENIGN NEOPLASM OF MAJOR SALIVARY GLANDS,NEOPLASMS,22,ON CAMPUS-OUTPATIENT HOSPITAL,...,51,M,23422,19334.30,4036.0,201901,43466,201901,43466,0
3,306668065,492733302,D120,BENIGN NEOPLASM OF CECUM,Benign,D12,BENIGN NEOPLASM OF COLON RECTUM ANUS ANAL CANAL,NEOPLASMS,24,AMBULATORY SURGICAL CNTR,...,47,M,23938,1300.00,0.0,201901,43466,201901,43466,0
4,992601593,492715708,D120,BENIGN NEOPLASM OF CECUM,Benign,D12,BENIGN NEOPLASM OF COLON RECTUM ANUS ANAL CANAL,NEOPLASMS,11,OFFICE,...,47,M,29242,1000.00,0.0,201901,43466,201901,43466,0
5,37090906,492889730,D472,MONOCLONAL GAMMOPATHY,Uncertain,D47,OTH NEOPLASM UNCERT BHV LYMPHOID HP & REL TISS,NEOPLASMS,81,INDEPENDENT LABORATORY,...,60,M,27260,46.00,0.0,201901,43466,201901,43466,0

In [12]:
import mitosheet
mitosheet.sheet

ModuleNotFoundError: No module named 'mitosheet'

In [13]:
print(Claims_df[col].unique)

NameError: name 'col' is not defined

In [10]:
Claims_df['Claim_Key'].unique

KeyError: 'Claim_Key'

In [12]:
Claims_df['CLAIM_KEY'].unique

<bound method Series.unique of 0         78266357
1         70650677
2        726223583
3        306668065
4        992601593
           ...
31569    647940595
31570    647940595
31571    685257057
31572    685257057
31573    685257057
Name: CLAIM_KEY, Length: 31574, dtype: int64>

In [13]:
Claims_df['BILL_AMT_CALC'].mean()

1529.12589313991

In [19]:
AggregatedClaims_df = Claims_df.groupby('CLAIM_KEY').sum()

In [18]:
Claims_df.groupby('CLAIM_KEY').agg({'BILL_AMT_CALC': ['min'],'PMT_AMT_CALC':['min']})

          BILL_AMT_CALC PMT_AMT_CALC
                    min          min
CLAIM_KEY
41511             31.00         9.07
104468            90.05         2.34
203275           322.08        12.10
207658           178.00        67.64
210426           223.00        71.67
...                 ...          ...
999568409        178.00        67.64
999638959         11.48         3.85
999655898        160.00        60.70
999673044        119.00        14.98
999677832       2095.33         0.00

[10313 rows x 2 columns]

In [24]:
AggregatedClaims_df.describe(include='all')

,SVC_LN_KEY,PLACE_OF_SVC_CD,NDC_PHARM_ONLY,PAT_AGE,PROC_SVC_KEY,BILL_AMT_CALC,PMT_AMT_CALC,SVC_BEG_DT,Service_Beg_Date,SVC_END_DT,Service_End_Date,Difference
count,1.0313e+04,10313.0000,1.0313e+04,10313.0000,1.0313e+04,10313.0000,10313.0000,1.0313e+04,1.0313e+04,1.0313e+04,1.0313e+04,10313.0000
mean,2.0271e+09,124.9218,7.1747e+08,164.0182,7.1202e+04,4681.5302,974.0586,6.1831e+05,1.3416e+05,6.1831e+05,1.3416e+05,1.7557
std,3.0803e+09,171.8804,6.5921e+09,262.4688,9.7387e+04,16970.7633,4632.9317,9.5739e+05,2.0752e+05,9.5739e+05,2.0753e+05,38.0032
min,4.8994e+08,1.0000,0.0000e+00,0.0000,0.0000e+00,0.0000,0.0000,2.0190e+05,4.3466e+04,2.0190e+05,4.3466e+04,0.0000
25%,6.2753e+08,22.0000,0.0000e+00,55.0000,2.7970e+04,115.0000,12.3300,2.0200e+05,4.3831e+04,2.0200e+05,4.3831e+04,0.0000
50%,1.0148e+09,81.0000,0.0000e+00,66.0000,3.0611e+04,323.0000,56.0600,2.0201e+05,4.4136e+04,2.0201e+05,4.4136e+04,0.0000
75%,1.9617e+09,162.0000,0.0000e+00,152.0000,7.6771e+04,1311.5900,267.9500,6.0574e+05,1.3140e+05,6.0574e+05,1.3140e+05,0.0000
max,4.1427e+10,2349.0000,1.0372e+11,3976.0000,1.0060e+06,552824.6800,199214.9700,1.1307e+07,2.4511e+06,1.1307e+07,2.4511e+06,992.0000